-- AlterTable
ALTER TABLE `Usuario` ADD COLUMN `ativo` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `cargo` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `numero` VARCHAR(191) NOT NULL DEFAULT '';
